runtime: python27
api_version: 1
threadsafe: yes
service: default

handlers:

# [START Admin]
- url: /admin/.*
  script: source.admin.Routes.app
# [END Admin]

# [START API services]
- url: /api/.*
  script: source.api.Routes.app
# [END API services]

# [START static content]
- url: /css
  static_dir: templates/css
- url: /js
  static_dir: templates/js
- url: /images
  static_dir: templates/images
# [END static content]

# [START webapp views]
- url: /.*
  script: source.views.Routes.app
# [START webapp views]

# [START libraries]
libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
- name: pycrypto
  version: latest
- name: flask
  version: latest
- name: ssl
  version: latest
# [END libraries]
